// 类别与图标的映射
export const categoryIcons = {
    全部: 'fa-solid fa-th-large',
    聊天对话: 'fa-solid fa-comments',
    写作助手: 'fa-solid fa-pen-nib',
    图像生成: 'fa-solid fa-image',
    艺术创作: 'fa-solid fa-palette',
    视频制作: 'fa-solid fa-film',
    音频制作: 'fa-solid fa-music',
    语音合成: 'fa-solid fa-microphone-alt',
    语音识别: 'fa-solid fa-ear-listen',
    编程开发: 'fa-solid fa-code',
    生产力工具: 'fa-solid fa-briefcase',
    办公助手: 'fa-solid fa-desktop',
    营销工具: 'fa-solid fa-bullhorn',
    设计工具: 'fa-solid fa-bezier-curve',
    教育工具: 'fa-solid fa-graduation-cap',
    语言学习: 'fa-solid fa-language',
    学习工具: 'fa-solid fa-bookmark',
    开源工具: 'fa-solid fa-code-branch',
    创意工具: 'fa-solid fa-wand-magic-sparkles',
    内容创作: 'fa-solid fa-feather-pointed',
    搜索引擎: 'fa-solid fa-magnifying-glass',
    社交助手: 'fa-solid fa-user-group',
    娱乐服务: 'fa-solid fa-gamepad',
    中文优化: 'fa-solid fa-font',
    文档处理: 'fa-solid fa-file-lines',
}
