name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # 选择合适的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # 确保在 package.json 中有定义 build 脚本

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 确保这个目录是你的构建输出目录

# 添加权限设置
permissions:
  contents: write
